language: go
go:
  - 1.1
  - 1.2
before_script:
- git clone https://github.com/sstephenson/bats.git
- cd bats && sudo ./install.sh /usr/local
script:
- bats test
notifications:
  email: github+go-git-duet@modcloth.com
